/**
 * Embeds wikipedia page content in a basic template with the page title.
 * 
 * TODO: consider using a streaming templating engine for performance.
 * 
 * @param {string} content - the page content fetched from Wikipedia
 * @param {string} id - the id of the page, for crediting the source
 * @param {string} pageTitle - the title of the page, fetched from wikipedia
 * @returns {string} the formatted HTML page
 */
function fillTemplate(content, id, pageTitle) {
    return `
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js">        <![endif]-->

<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" type="image/x-icon" href="/wiki-races/favicon.png" />
    <title>INTERalliance Wiki Races</title>
    <meta name="description"
        content="A website to host challenges where people try to get from one Wikipedia page to another, as quick as possible.">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../wiki.css">
    <link rel="stylesheet" href="../wiki-custom.css">
</head>

<body class="outer-wrapper">

    <h1 class="autogenerated page-title">
        ${pageTitle}
    </h1>

    ${content}

    <center style="padding: 1em; padding-bottom: 4.5em;">
        This page uses material from
        the Wikipedia article <u>https://en.wikipedia.org/wiki/${id}</u>
        which is released under the Creative Commons
        Attribution-Share-Alike License 3.0. <br />
        A copy of this license can be found at <u>https://creativecommons.org/licenses/by-sa/3.0/</u>. </br>
        This article was procedurally modified to remove content that would hurt the game experience.
    </center>
</body>

</html>
`;
}

module.exports = {
    fillTemplate,
};
