version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - 27017:27017 # bind $(mongodb local port):$(mongodb container port)
    volumes:
      - mongo_data:/data/db
  app:
    depends_on:
      - mongodb
    build: ./
    restart: unless-stopped
    ports:
      - 8443:8443 # bind $(node local port):$(node container port)
    environment:
      - MONGODB_URL="mongodb://mongodb:27017/"
    stdin_open: true # TODO: should these be enabled for production
    tty: true
    volumes:
      - "./src/game/game_static:/wiki-races/src/game/game_static:ro" # game static is read only
      - "./src/game/cache:/wiki-races/src/game/cache" # cache can read and write

volumes:
  mongo_data: {}

